name: magicslides_app
description: A Flutter app for generating presentations using MagicSlides API
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  get: ^4.6.6
  
  # Backend
  supabase_flutter: ^2.3.4
  
  # HTTP & API
  http: ^1.2.0
  dio: ^5.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  
  # PDF Viewer
  flutter_pdfview: ^1.3.2
  syncfusion_flutter_pdfviewer: ^27.1.48
  
  # File Download & Permissions
  permission_handler: ^11.2.0
  flutter_downloader: ^1.11.6
  
  # UI Components
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  cached_network_image: ^3.3.1
  device_info_plus: ^10.1.0
  open_file: ^3.3.2
  
  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.4
  connectivity_plus: ^5.0.2
  flutter_launcher_icons: ^0.13.1


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
flutter:
  uses-material-design: true
  
  assets:
    - assets/icon/